# Practical 8

**Aim:** Calculate and interpret descriptive statistics: mean, median, mode, variance, standard deviation, range, quartiles and IQR on a given dataset.

### 1. Load Dataset and View Head

In [1]:
import pandas as pd

df = pd.read_csv("employee.csv")
df.head()

   Age Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
0   41       Yes  ...                       0                     5
1   49        No  ...                       1                     7
2   37       Yes  ...                       0                     0
3   33        No  ...                       3                     0
4   27        No  ...                       2                     2

[5 rows x 35 columns]

### 2. Last 5 Records

In [3]:
df.tail(5)

      Age Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
1465   36        No  ...                       0                     3
1466   39        No  ...                       1                     7
1467   27        No  ...                       0                     3
1468   49        No  ...                       0                     8
1469   34        No  ...                       1                     2

[5 rows x 35 columns]

### 3. Select Integer Columns

In [4]:
df.select_dtypes("int")

      Age  DailyRate  ...  YearsSinceLastPromotion  YearsWithCurrManager
0      41       1102  ...                        0                     5
1      49        279  ...                        1                     7
2      37       1373  ...                        0                     0
3      33       1392  ...                        3                     0
4      27        591  ...                        2                     2
...   ...        ...  ...                      ...                   ...
1465   36        884  ...                        0                     3
1466   39        613  ...                        1                     7
1467   27        155  ...                        0                     3
1468   49       1023  ...                        0                     8
1469   34        628  ...                        1                     2

[1470 rows x 26 columns]

### 4. Maximum and Minimum Values

In [5]:
print("Maximum Monthly Income:", df["MonthlyIncome"].max())
print("Minimum Monthly Income:", df["MonthlyIncome"].min())

Maximum Monthly Income: 19999
Minimum Monthly Income: 1009

### 5. Measures of Central Tendency

In [6]:
print("Measure of Central Tendency")
print("Mean:", df["MonthlyIncome"].mean())
print("Median:", df["MonthlyIncome"].median())
print("Mode:", df["MonthlyIncome"].mode()[0])

Measure of Central Tendency
Mean: 6502.931292517007
Median: 4919.0
Mode: 2342

### 6. Measures of Spread

In [7]:
print("Measure of Spread")
print("Range:", df["MonthlyIncome"].max() - df["MonthlyIncome"].min())
print("Variance:", df["MonthlyIncome"].var())
print("Standard Deviation:", df["MonthlyIncome"].std())

Measure of Spread
Range: 18990
Variance: 22164857.07151841
Standard Deviation: 4707.956783097994

### 7. Quartiles and Interquartile Range (IQR)

In [8]:
# Quartiles
q1 = df["MonthlyIncome"].quantile(0.25)
q2 = df["MonthlyIncome"].quantile(0.50)
q3 = df["MonthlyIncome"].quantile(0.75)
iqr = q3 - q1

print("Q1 (25%):", q1)
print("Q2 (50% / Median):", q2)
print("Q3 (75%):", q3)
print("IQR:", iqr)

Q1 (25%): 2911.0
Q2 (50% / Median): 4919.0
Q3 (75%): 8379.0
IQR: 5468.0

### 8. Correlation Coefficient

In [9]:
print("Correlation Coefficient")
print("Age vs MonthlyIncome:", df["Age"].corr(df["MonthlyIncome"]))

Correlation Coefficient
Age vs MonthlyIncome: 0.4978545669265806