# Practical 09

**Aim:** Demonstrate the data science life cycle and perform Univariate, Bivariate and Multivariate analysis on a real-world dataset.

In [1]:
import pandas as pd

df = pd.read_csv("employee.csv")

### 1. Univariate

In [2]:
df["MonthlyIncome"].describe()

count     1470.000000
mean      6502.931293
std       4707.956783
min       1009.000000
25%       2911.000000
50%       4919.000000
75%       8379.000000
max      19999.000000
Name: MonthlyIncome, dtype: float64

### 2. Bivariate

In [3]:
df[["Age", "TotalWorkingYears"]].describe()

               Age  TotalWorkingYears
count  1470.000000        1470.000000
mean     36.923810          11.279592
std       9.135373           7.780782
min      18.000000           0.000000
25%      30.000000           6.000000
50%      36.000000          10.000000
75%      43.000000          15.000000
max      60.000000          40.000000

### 3. Multivariate

In [4]:
df[["YearsAtCompany", "YearsInCurrentRole", "YearsWithCurrManager"]].describe()

       YearsAtCompany  YearsInCurrentRole  YearsWithCurrManager
count     1470.000000         1470.000000           1470.000000
mean         7.008163            4.229252              4.123129
std          6.126525            3.623137              3.568136
min          0.000000            0.000000              0.000000
25%          3.000000            2.000000              2.000000
50%          5.000000            3.000000              3.000000
75%          9.000000            7.000000              7.000000
max         40.000000           18.000000             17.000000